### ISSUE TITLE
请问要抢不同时间的套票要怎么改，是这样吗

### ISSUE THREAD

**Issue by Reinborn** [bloodbaby/TI-tickets#2]
var cc3 = document.querySelector('body > div.perform > div > div.flex1 > div.hd > div > div.order > div.perform__order__box > div.perform__order__select.perform__order__select__performs > div.select_right > div > div:nth-child(6)')
			cc3.click()

**Comment by bloodbaby** [comment]
是的，改完建议console里面测试一下
